### ISSUE TITLE
Recommend to follow project's rule if it conflicts with the suggested rule

### ISSUE THREAD

**Issue by pksadiq** [cbeams/chris.beams.io#45]
Hi,
   I do always recommend people to refer the page https://chris.beams.io/posts/git-commit/ for "How to write a good commit message."

But I feel some important recommendation missing there. That is, if any of the rules conflicts with the project's rule, the project's rule should be taken into action. This may be added as rule 0 (or 8).

Say for example the guix commit messages always end up with a period: http://git.savannah.gnu.org/cgit/guix.git/log/

Thanks for a good article

**Comment by cbeams** [comment]
Hi @pksadiq, thanks for the feedback, but I believe this is already captured in the doc, if somewhat implicitly. The introduction makes it clear that teams should define their own commit message guidelines and follow them. The "seven rules" presented in the next section are an "off the shelf" answer to how to write commit messages for teams who do not have any reason or desire to define their own approach.

So I'll close this now, but thanks again.
