### ISSUE TITLE
Can't find applicable licence for your content

### ISSUE THREAD

**Issue by devcurmudgeon** [cbeams/chris.beams.io#48]
Hi Chris,
I would like to re-use some of your commit-message article in a corporate standard I'm helping a customer with. Please could you confirm if you are happy with this? I wasn't able to find a licence at https://chris.beams.io or in the git repo
br
Paul

**Comment by cbeams** [comment]
Please do; view source and you’ll see it’s CC-licensed. Thanks for asking in any case.

**Comment by tyll** [comment]
Thanks, I was having the same question. For others coming in the future, it is visible here: https://github.com/cbeams/chris.beams.io/blob/d28b7280f04725b95dc9d4a84c2e24f72c91b519/_layouts/default.html#L7
